var searchData=
[
  ['gamecontrol',['GameControl',['../class_class_repository_1_1_xml_handler_1_1_game_control.html',1,'ClassRepository.XmlHandler.GameControl'],['../class_display_1_1_game_display_1_1_game_control.html',1,'Display.GameDisplay.GameControl']]],
  ['gameitem',['GameItem',['../class_class_repository_1_1_game_item.html',1,'ClassRepository.GameItem'],['../class_class_repository_1_1_game_item.html#a606e3bce9ed02c32343a5fd781e8987e',1,'ClassRepository.GameItem.GameItem()'],['../class_class_repository_1_1_game_item.html#aa4f1161e9d266d71062e13a693a9c6f4',1,'ClassRepository.GameItem.GameItem(double x, double y)']]],
  ['gamelogic',['GameLogic',['../class_space_invader_logic_1_1_game_logic.html',1,'SpaceInvaderLogic.GameLogic'],['../class_space_invader_logic_1_1_game_logic.html#af5a821d82c2c26a119ed8c3532f28ed5',1,'SpaceInvaderLogic.GameLogic.GameLogic(string filePath)'],['../class_space_invader_logic_1_1_game_logic.html#a001fa7b0ac95f8d5dd093989a5e53b2b',1,'SpaceInvaderLogic.GameLogic.GameLogic()']]],
  ['gamelogictest',['GameLogicTest',['../class_space_invader_logic_1_1_test_1_1_game_logic_test.html',1,'SpaceInvaderLogic::Test']]],
  ['gamemodel',['GameModel',['../class_class_repository_1_1_game_model.html',1,'ClassRepository.GameModel'],['../class_class_repository_1_1_game_model.html#a36b0da058e6205dc7b1cc9def5eb4d9a',1,'ClassRepository.GameModel.GameModel()'],['../class_class_repository_1_1_game_model.html#a40ce59cc5cc33b45bf45bd695ca8df80',1,'ClassRepository.GameModel.GameModel(List&lt; Ufo &gt; ufos, List&lt; Projectile &gt; projectiles, List&lt; Shield &gt; shields, Player player, GameState gamestate=GameState.Paused, int score=0)']]],
  ['gamerepository',['GameRepository',['../class_class_repository_1_1_repository_1_1_game_repository.html',1,'ClassRepository::Repository']]],
  ['gamestate',['GameState',['../class_class_repository_1_1_game_model.html#ae0839aebcca84ec1dcddfa57830a0f2f',1,'ClassRepository.GameModel.GameState()'],['../interface_class_repository_1_1_model_1_1_i_game_model.html#a2928165877efaed0e95ed9d3cd0d9be8',1,'ClassRepository.Model.IGameModel.GameState()'],['../namespace_class_repository.html#a7d13c3525be7c204b0ae7d7754ebce34',1,'ClassRepository.GameState()']]],
  ['gamestateswitch',['GameStateSwitch',['../interface_space_invader_logic_1_1_interfaces_1_1_i_game_logic.html#a8e94ef4cb874be072e8394a08c0636b3',1,'SpaceInvaderLogic.Interfaces.IGameLogic.GameStateSwitch()'],['../class_space_invader_logic_1_1_game_logic.html#a5232115455bf6e5461fd0bbb7bac3c90',1,'SpaceInvaderLogic.GameLogic.GameStateSwitch()']]],
  ['generatedinternaltypehelper',['GeneratedInternalTypeHelper',['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html',1,'XamlGeneratedNamespace']]],
  ['getpropertyvalue',['GetPropertyValue',['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#afdc9fe15b56607d02082908d934480c6',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.GetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, System.Globalization.CultureInfo culture)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#afdc9fe15b56607d02082908d934480c6',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.GetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, System.Globalization.CultureInfo culture)']]],
  ['globalsettings',['GlobalSettings',['../namespace_global_settings.html',1,'']]]
];
