var NAVTREEINDEX1 =
{
"namespace_class_repository_1_1_xml_handler.html":[3,0,0,2],
"namespace_class_repository_1_1_xml_handler.html":[2,0,0,2],
"namespace_display.html":[2,0,1],
"namespace_display.html":[3,0,1],
"namespace_display_1_1_game_display.html":[2,0,1,0],
"namespace_display_1_1_game_display.html":[3,0,1,0],
"namespace_display_1_1_properties.html":[2,0,1,1],
"namespace_global_settings.html":[2,0,2],
"namespace_global_settings.html":[3,0,2],
"namespace_space_invader_logic.html":[3,0,3],
"namespace_space_invader_logic.html":[2,0,3],
"namespace_space_invader_logic_1_1_interfaces.html":[3,0,3,0],
"namespace_space_invader_logic_1_1_interfaces.html":[2,0,3,0],
"namespace_space_invader_logic_1_1_test.html":[2,0,3,1],
"namespace_space_invader_logic_1_1_test.html":[3,0,3,1],
"namespace_xaml_generated_namespace.html":[3,0,4],
"namespace_xaml_generated_namespace.html":[2,0,4],
"namespacemembers.html":[2,1,0],
"namespacemembers_enum.html":[2,1,1],
"namespaces.html":[2,0],
"pages.html":[]
};
